"""create_cart_and_catalog_tables

Revision ID: 7c1e6978b6cb
Revises: b2475b2ba676
Create Date: 2025-12-13 04:24:32.363484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c1e6978b6cb'
down_revision: Union[str, Sequence[str], None] = 'b2475b2ba676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
